### This file contains a table of advisories and the packages to which they apply ###
#
# The schema is relatively simple:
#   - Advisories are the top-level keys by ID
#       - if multiple aliases exist, prefer CVE over GHSA over EUVD
#   - Each advisory entry has Julia package names (without .jl suffix) as its keys
#   - The value for a particular advisory[package] is either:
#       - A list of GitHub Security Advisory style version ranges to which the advisory applies
#       - A string detailing _why_ a given advisory does not apply
#
# This file is semi-automatically updated by suggested pull requests. By marking a package with an
# exception string, you prevent further automatic updates from suggesting the advisory apply.

[CVE-2023-0465]
OpenSSL_jll = ["< 1.1.22+0", ">= 3.0.8+0, < 3.0.10+0"]
Openresty_jll = ["< 1.27.1+0"]
