name: Import GitHub Security Advisories

on:
  schedule:
    # Run at 3 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      repo:
        description: 'Fetch advisories for just one specific org or repository e.g., org/repo.jl'
        required: false
        type: string

jobs:
  fetch-advisories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'

    - name: Install Julia dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run advisory fetcher script
      run: |
        julia --project=. scripts/fetch_github_advisories.jl $RUNNER_TEMP/osv ${{ inputs.repo }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Import OSV files into `packages/General`
      run: |
        julia --project=. scripts/import_osv_advisories.jl $RUNNER_TEMP/osv

    - name: Check for changes
      id: git-check
      run: |
        [[ $(git ls-files --others --modified --exclude-standard) ]] && echo "changes=true" >> $GITHUB_OUTPUT || echo "no changes"
        [[ $(git ls-files --others --exclude-standard) ]] && echo "verb=added" >> $GITHUB_OUTPUT || echo "verb=updated" >> $GITHUB_OUTPUT
        echo "packages=$(git ls-files --others --modified --exclude-standard \
          | awk '/^packages\/General\/[^\/]+\/[^\/]+\.json$/ { split($0, parts, "/"); print parts[3] }' \
          | sort -u | paste -sd, -)" >> $GITHUB_OUTPUT
        echo "cves=$(git ls-files --others --modified --exclude-standard \
          | awk '/^packages\/General\/[^\/]+\/[^\/]+\.json$/ { split($0, parts, "/"); print parts[4] }' \
          | sort -u | paste -sd, -)" >> $GITHUB_OUTPUT
        echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        title: ${{ steps.git-check.outputs.verb }} ${{ steps.git-check.outputs.packages }}
        branch: ${{ inputs.repo != '' && inputs.repo != null && inputs.repo || steps.git-check.outputs.date }}
