name: Fetch NVD Security Advisories

on:
  schedule:
    # Run at 4 AM UTC every day
    - cron: '0 4 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-nvd-advisories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install Julia dependencies
      run: |
        julia --project=scripts -e 'using Pkg; Pkg.instantiate()'

    - name: Run NVD advisory fetcher script
      run: |
        julia --project=scripts scripts/fetch_nvd_advisories.jl
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    - name: Check for changes
      id: git-check
      run: |
        [[ $(git ls-files --others --modified --exclude-standard) ]] && echo "changes=true" >> $GITHUB_OUTPUT || echo "no changes"

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add packages/
        git commit -m "Update NVD security advisories - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push