name: Fetch GitHub Security Advisories

on:
  schedule:
    # Run at 3 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      repo:
        description: 'Fetch advisories for just one specific repository e.g., org/repo.jl'
        required: false
        type: string

jobs:
  fetch-advisories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install Julia dependencies
      run: |
        julia --project=scripts -e 'using Pkg; Pkg.instantiate()'

    - name: Run advisory fetcher script
      run: |
        julia --project=scripts scripts/fetch_github_advisories.jl ${{ inputs.repo }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: git-check
      run: |
        [[ $(git ls-files --others --modified --exclude-standard) ]] && echo "changes=true" >> $GITHUB_OUTPUT || echo "no changes"

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add packages/
        git commit -m "Update Julia security advisories - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push