name: Fetch NVD Security Advisories

on:
  schedule:
    # Run at 4 AM UTC every day
    - cron: '0 4 * * *'
  workflow_dispatch: # Allow manual triggering
    inputs:
      arg:
        description: 'Fetch advisories for just one specific CPE (e.g., `openssl:openssl`) or CVE'
        required: false
        type: string

jobs:
  fetch-nvd-advisories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1

    - name: Install Julia dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run NVD advisory fetcher script
      run: |
        julia --project=. scripts/fetch_nvd_advisories.jl $RUNNER_TEMP/osv ${{ inputs.repo }}
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    - name: Import OSV files into `packages/General`
      run: |
        julia --project=. scripts/import_osv_advisories.jl $RUNNER_TEMP/osv

    - name: Check for changes
      id: git-check
      run: |
        [[ $(git ls-files --others --modified --exclude-standard) ]] && echo "changes=true" >> $GITHUB_OUTPUT || echo "no changes"

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v7
