name: Search for upstream advisories

on:
  schedule:
    # Run once a day
    - cron: '0 5 */1 * *'
  workflow_dispatch:
    inputs:
      haystack:
        description: 'Advisory ID, package name, or list of package names'
        type: string
        default: ''
      filter:
        description: 'Filter results to only those that affect a Julia package or have significant updates'
        type: boolean
        default: true

permissions:
  contents: read

# Only allow one search to run at a time; queue subsequent runs
concurrency:
  group: search-upstream-advisories
  cancel-in-progress: false

jobs:
  identify-advisories:
    name: >-
      ${{
        github.event_name == 'schedule' && 'Ecosystem search (scheduled)'
        || (github.event_name == 'workflow_dispatch' && (inputs.haystack == '' || inputs.haystack == null) && 'Ecosystem search (manual)')
        || format('Search {0}', inputs.haystack)
      }}
    uses: ./.github/workflows/search-and-pr.yml
    with:
      haystack: ${{ inputs.haystack || '' }}
      filter: ${{ inputs.filter == null || inputs.filter }}
    secrets: inherit
