name: Sync upstream advisories

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  sync-upstream-advisories:
    if: github.event_name != 'pull_request_review' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
      env:
        GONOPROXY: github.com/google/osv

    - name: Install Julia dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Sync upstream advisories
      id: sync
      run: |
        julia --project=. scripts/sync_upstream_advisories.jl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    - name: Check for changes
      id: git-check
      run: |
        [[ $(git ls-files --others --modified --exclude-standard) ]] && echo "changes=true" >> $GITHUB_OUTPUT || echo "no changes"
        [[ $(git ls-files --others --exclude-standard) ]] && echo "additions=true" >> $GITHUB_OUTPUT || echo "no changes"

    - name: Auto-assign IDs if required
      if: steps.git-check.outputs.additions == 'true'
      run: |
        go install github.com/google/osv/vulnfeeds/cmd/ids@latest
        ids -dir=./packages -prefix DONOTUSEJLSEC -format json
      env:
        GONOPROXY: github.com/google/osv

    - name: Commit sync changes directly to the PR
      if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request_review'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add packages/
        git commit -m "${{ steps.sync.outputs.title }}"
        git push

    - name: Create Pull Request if not already on a PR
      if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request_review'
      uses: peter-evans/create-pull-request@v7
      with:
        title: ${{ steps.sync.outputs.title }}
        body: ${{ steps.sync.outputs.body }}
        branch: "sync-upstream-advisories"
