name: JSON Schema Validation
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For git diff

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install osv-linter
        run: |
          git clone https://github.com/JuliaComputing/osv-schema.git -b juliahub/julia
          cd ./osv-schema/tools/osv-linter
          go build -o ../../../osv-linter ./cmd/osv
          cd ../../..
          rm -rf osv-schema

      - name: Validate JSON
        run: |
          output=$(./osv-linter record lint packages 2>&1 || true)
          if [ -n "$output" ]; then
            echo "$output"
            exit 1
          fi
